// <auto-generated />
using System;
using CourierSystemDataLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourierSystemDataLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230508164220_boolean orderstatus introduced")]
    partial class booleanorderstatusintroduced
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourierSystemDataLayer.Model.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("CourierSystemDataLayer.Model.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ConsignmentNumber")
                        .HasColumnType("int");

                    b.Property<string>("CurrentPlace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinalDateToReachDestination")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderPlacingDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OrderStatus")
                        .HasColumnType("bit");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("CourierSystemDataLayer.Model.Recipant", b =>
                {
                    b.Property<string>("RecipantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecipantId");

                    b.ToTable("recipants");
                });

            modelBuilder.Entity("CourierSystemDataLayer.Model.Shipment", b =>
                {
                    b.Property<string>("ShipmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ShipmentArrivedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShipmentDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShipmentSentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShipmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShipmentId");

                    b.ToTable("shipments");
                });
#pragma warning restore 612, 618
        }
    }
}
